### ISSUE TITLE
I'm having this problem on GLITCH

### ISSUE THREAD

**Issue by caspiannn** [noahmarshall12/superman#2]
```TypeError: Cannot read property 'playingnow' of undefined
at Object.mod (/app/actions/mod_info_MOD.js:395:23)
at Object.<anonymous> (/app/js/Actions.js:79:13)
    at Array.forEach (<anonymous>)
at Object.Actions.initMods (/app/js/Actions.js:73:32)
at Object.Files.initStandalone (/app/js/Files.js:27:11)
at Object.<anonymous> (/app/bot.js:38:7)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
=====================================================
==================== DBM NETWORK ====================
The DBM Network Mods are only meant to run on the
Beta version of DBM! Please upgrade on steam, then
try again, you may haveto make a new project and copy
your data over!
=====================================================```

**Comment by altgen** [comment]
then upgrade to beta you dumbdumb

**Comment by caspiannn** [comment]
pardon? i'm reporting bug when using the Superman after he updated the DBM mods to 1.9.5. that's why there is error.

**Comment by noahmarshall12** [comment]
@caspiannn I have made changes that should fix this issue. If you still encounter errors, let me know.

You can see that here (#3) if you'd like.
